CREATE TABLE Users(
  id SERIAL UNIQUE NOT NULL ,
  login VARCHAR(50) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  email VARCHAR(50),
  phone VARCHAR(50),
  admin BOOLEAN DEFAULT FALSE
);


CREATE TABLE Category(
  id SERIAL UNIQUE NOT NULL ,
  title VARCHAR(50) NOT NULL ,
  image VARCHAR(255) NOT NULL
);

CREATE TABLE Dish(
  id SERIAL UNIQUE NOT NULL ,
  title VARCHAR(50) NOT NULL ,
  description VARCHAR(255),
  image VARCHAR(255) NOT NULL ,
  category_id INT NOT NULL,
  price INT DEFAULT 0 NOT NULL  ,
  sale BOOLEAN DEFAULT FALSE NOT NULL,
  discount INT DEFAULT 0 NOT NULL,
  FOREIGN KEY (category_id) REFERENCES category (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Tables(
  id SERIAL UNIQUE  NOT NULL,
  posx DOUBLE PRECISION NOT NULL,
  posy DOUBLE PRECISION NOT NULL
);

CREATE TABLE Booking(
  id SERIAL UNIQUE NOT NULL,
  booker VARCHAR(50) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  start TIMESTAMP  NOT NULL,
  end_time TIMESTAMP NOT NULL ,
  table_id INT NOT NULL,
  FOREIGN KEY (table_id) REFERENCES tables (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Cart_items(
  id SERIAL UNIQUE NOT NULL ,
  user_id INT NOT NULL,
  dish_id INT NOT NULL,
  count INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (dish_id) REFERENCES dish (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Orders(
  id SERIAL UNIQUE NOT NULL ,
  user_id INT NOT NULL ,
  order_total INT NOT NULL,
  created TIMESTAMP NOT NULL,
  status VARCHAR(30) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE Order_item(
  id SERIAL UNIQUE NOT NULL,
  order_id INT NOT NULL,
  dish_id INT NOT NULL,
  count INT NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (dish_id) REFERENCES dish (id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
)