CREATE TABLE Users(
  id SERIAL NOT NULL ,
  login VARCHAR(50) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  email VARCHAR(50),
  phone VARCHAR(50),
  admin BOOLEAN DEFAULT FALSE
);


CREATE TABLE Category(
  id SERIAL NOT NULL ,
  title VARCHAR(50) NOT NULL ,
  image VARCHAR(255) NOT NULL
);

CREATE TABLE Dish(
  id SERIAL NOT NULL ,
  title VARCHAR(50) NOT NULL ,
  description VARCHAR(255),
  image VARCHAR(255) NOT NULL ,
  category_id INT NOT NULL,
  price INT DEFAULT 0 NOT NULL  ,
  sale BOOLEAN DEFAULT FALSE NOT NULL,
  discount INT DEFAULT 0 NOT NULL
);

CREATE TABLE Tables(
  id SERIAL NOT NULL,
  posx DOUBLE PRECISION NOT NULL,
  posy DOUBLE PRECISION NOT NULL
);

CREATE TABLE Booking(
  id SERIAL NOT NULL,
  booker VARCHAR(50) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  start TIMESTAMP  NOT NULL,
  end_time TIMESTAMP NOT NULL ,
  table_id INT NOT NULL
);

CREATE TABLE Cart_items(
  id SERIAL NOT NULL ,
  user_id INT NOT NULL,
  dish_id INT NOT NULL,
  count INT NOT NULL
);

CREATE TABLE Orders(
  id SERIAL NOT NULL ,
  user_id INT NOT NULL ,
  order_total INT NOT NULL
);

CREATE TABLE Order_item(
  id SERIAL NOT NULL,
  order_id INT NOT NULL,
  dish_id INT NOT NULL,
  count INT NOT NULL
)